# -*- coding: utf-8 -*-
"""25simulador_web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SD1AveuP9OZlYt5SaiGLBVHueXAbLaMv
"""

import streamlit as st
import random
import time

# Funções ajustadas para gerar contas por nível
def gerar_conta(nivel, operacao):
    """
    Gera uma pergunta de matemática com base no nível e operação.

    Args:
        nivel (str): 'básico', 'intermediário' ou 'avançado'.
        operacao (str): 'Adição', 'Subtração', 'Multiplicação' ou 'Divisão'.

    Returns:
        tuple: Uma tupla contendo a pergunta (str) e a resposta correta (float).
               Retorna (None, None) se a operação não for suportada ou se houver erro na geração.
    """
    try:
        if operacao not in ['Multiplicação', 'Adição', 'Subtração', 'Divisão']:
            return None, None

        if nivel == 'básico':
            max_val = 9
        elif nivel == 'intermediário':
            max_val = 99
        elif nivel == 'avançado':
            max_val = 999
        else:
            return None, None

        if operacao == 'Multiplicação':
            num1 = random.randint(1, 99)
            num2 = random.randint(1, max_val)
            pergunta = f"{num1} x {num2}"
            resultado = float(num1 * num2)
        elif operacao == 'Adição':
            num1 = random.randint(1, 99)
            num2 = random.randint(1, max_val)
            pergunta = f"{num1} + {num2}"
            resultado = float(num1 + num2)
        elif operacao == 'Subtração':
            num2 = random.randint(1, max_val)
            num1 = random.randint(num2, 99 + max_val) # Garante resultado não negativo
            pergunta = f"{num1} - {num2}"
            resultado = float(num1 - num2)
        elif operacao == 'Divisão':
            num2 = random.randint(1, max_val)
            resultado = random.randint(1, 99)
            num1 = num2 * resultado
            pergunta = f"{num1} ÷ {num2}"
            resultado = float(resultado)
        return pergunta, resultado

    except Exception as e:
        st.error(f"Erro ao gerar pergunta: {e}")
        return None, None

def mostrar_dicas():
    """Exibe dicas de estudo."""
    dicas = [
        "Pratique tabuada diariamente.",
        "Use jogos online para aprender matemática.",
        "Resolva exercícios de diferentes níveis de dificuldade.",
        "Estude com amigos e expliquem os conceitos uns aos outros.",
        "Consulte um professor se tiver dúvidas.",
        "Use aplicativos de matemática para praticar.",
        "Tente resolver problemas de matemática mentalmente.",
        "Relacione a matemática com situações do dia a dia.",
        "Não tenha medo de errar, o erro faz parte do aprendizado.",
        "Mantenha uma atitude positiva em relação à matemática."
    ]
    st.markdown("---")
    st.subheader("Dicas de Estudo 🧠")
    for dica in dicas:
        st.markdown(f"✨ {dica}")

# Configuração inicial do Streamlit
st.set_page_config(page_title="Simulador de Operações Basicas de  Mátematicas", page_icon="🧮")

# Gerenciamento de estado da sessão
if 'etapa' not in st.session_state:
    st.session_state.etapa = 'configuração'
    st.session_state.respostas = []
    st.session_state.start_time = 0
    st.session_state.nome = ""
    st.session_state.nivel = ""
    st.session_state.perguntas = []
    st.session_state.respostas_corretas = []
    st.session_state.tempo_total = 0
    st.session_state.operacoes_selecionadas = ['Multiplicação', 'Adição', 'Subtração', 'Divisão'] # Nomes das operações

# Página de configuração inicial
if st.session_state.etapa == 'configuração':
    st.title("Simulador de Operações Básicas de Matemáticas 🧮")

    nome = st.text_input("Digite seu nome:", value=st.session_state.nome).upper()
    nivel_opcoes = {
        "1 - Básico": "básico",
        "2 - Intermediário": "intermediário",
        "3 - Avançado": "avançado",
    }
    nivel_selecionado_texto = st.selectbox("Escolha o nível:", list(nivel_opcoes.keys()), index=0)
    nivel = nivel_opcoes[nivel_selecionado_texto]

    # Checkbox para selecionar operações com nomes
    operacoes_nomes = ["Multiplicação", "Adição", "Subtração", "Divisão"]
    operacoes_selecionadas = st.multiselect(
        "Selecione as operações:",
        operacoes_nomes,
        default=st.session_state.operacoes_selecionadas
    )
    st.session_state.operacoes_selecionadas = operacoes_selecionadas # Atualiza o estado da sessão

    if st.button("Iniciar Simulação!"):
        if not nome:
            st.error("Por favor, digite seu nome.")
        elif not operacoes_selecionadas:
            st.error("Por favor, selecione pelo menos uma operação.")
        else:
            st.session_state.etapa = 'simulação'
            st.session_state.nome = nome
            st.session_state.nivel = nivel
            st.session_state.perguntas = []
            st.session_state.respostas_corretas = []

            # Gerar todas as perguntas COM as operações selecionadas
            for op in operacoes_selecionadas:
                for _ in range(5):
                    pergunta, resposta = gerar_conta(nivel, op)
                    if pergunta:
                        st.session_state.perguntas.append(pergunta)
                        st.session_state.respostas_corretas.append(resposta)

            st.session_state.respostas = [None] * len(st.session_state.perguntas)
            st.session_state.start_time = time.time()
            st.rerun()


# Página da simulação
elif st.session_state.etapa == 'simulação':
    st.title(f"Vamos lá, {st.session_state.nome}! 🚀")

    tempo_decorrido = time.time() - st.session_state.start_time
    tempo_restante = max(600 - int(tempo_decorrido), 0)
    st.progress(tempo_restante / 600)
    minutes = tempo_restante // 60
    seconds = tempo_restante % 60
    st.caption(f"Tempo restante: {minutes:02d}:{seconds:02d}")

    with st.form("respostas_form"):
        # Organizar perguntas por operação
        for i, pergunta in enumerate(st.session_state.perguntas):
                resposta_str = st.text_input(label=f"({i + 1}) {pergunta}", key=f"q_{i}",
                                            value=st.session_state.respostas[i] if st.session_state.respostas[i] is not None else "")
                st.session_state.respostas[i] = resposta_str  # Armazena a resposta como string

        if st.form_submit_button("Enviar Respostas"):
            # Validação e conversão das respostas para float
            respostas_float = []
            for i, resposta_str in enumerate(st.session_state.respostas):
                try:
                    resposta_float = float(
                        resposta_str.replace(",", "."))  # Converte para float, tratando vírgula como decimal
                    respostas_float.append(resposta_float)
                except ValueError:
                    respostas_float.append(None)  # Se a conversão falhar, mantém como None

            st.session_state.respostas = respostas_float  # atualiza para float
            st.session_state.etapa = 'resultados'
            st.session_state.tempo_total = time.time() - st.session_state.start_time
            st.rerun()



# Página de resultados
elif st.session_state.etapa == 'resultados':
    st.title("Resultados 📊")

    acertos = 0
    detalhes = []
    for i, (resposta_usuario, resposta_correta) in enumerate(zip(
            st.session_state.respostas,
            st.session_state.respostas_corretas
    )):
        if resposta_usuario is not None:
            if abs(resposta_usuario - resposta_correta) < 0.01:
                acertos += 1
                detalhes.append(f"✅ ({i + 1}) {st.session_state.perguntas[i]} = {resposta_usuario:.2f}")
            else:
                detalhes.append(
                    f"❌ ({i + 1}) {st.session_state.perguntas[i]} = {resposta_usuario:.2f} (Correto: {resposta_correta:.2f})")
        else:
            detalhes.append(
                f"❓ ({i + 1}) {st.session_state.perguntas[i]} = Não respondido (Correto: {resposta_correta:.2f})")

    total_questoes = len(st.session_state.respostas)
    percentual_acertos = (acertos / total_questoes) * 100 if total_questoes > 0 else 0
    percentual_erros = 100 - percentual_acertos

    st.subheader("Desempenho:")
    col1, col2, col3 = st.columns(3)
    col1.metric("Acertos", f"{int(acertos)} ({percentual_acertos:.2f}%)")
    col2.metric("Erros", f"{int(total_questoes - acertos)} ({percentual_erros:.2f}%)")
    col3.metric("Tempo Total", f"{int(st.session_state.tempo_total // 60)}:{int(st.session_state.tempo_total % 60):02d}")

    st.subheader("Detalhes das Respostas:")
    for item in detalhes:
        st.markdown(item)

    if percentual_acertos <= 69:
        st.subheader("Mensagem Motivacional:")
        st.markdown(random.choice([
            "Não desanime! A prática leva à perfeição. Continue se esforçando! 💪",
            "Você está aprendendo! Cada erro é uma oportunidade para melhorar. 🚀",
            "Mantenha o foco e a determinação. Você vai chegar lá! 🔥",
            "Acredite em si mesmo! Com dedicação, você conquista seus objetivos. 🌟",
            "O importante é não desistir! Persista e você verá o progresso. 💯"
        ]))
    else:
        st.subheader("Mensagem Motivacional:")
        st.markdown(random.choice([
            "Parabéns! Você está arrasando! Continue assim! 🎉",
            "Excelente desempenho! Você tem um ótimo domínio da matemática. 👍",
            "Muito bem! Seu esforço está trazendo resultados incríveis! 🏆",
            "Você é um gênio! Continue brilhando! 🌟",
            "Show de bola! Você está no caminho certo para o sucesso! 💯"
        ]))

    mostrar_dicas()

    if st.button("Nova Simulação"):
        st.session_state.clear()
        st.rerun()