# -*- coding: utf-8 -*-
"""app_tabuada7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bih-iY15BzA_1GYYDm6vikbk1Q790AcE
"""

import streamlit as st
import random
from gtts import gTTS
import os
import time
import pandas as pd
import plotly.express as px

# --- Configurações Iniciais ---
TOTAL_PERGUNTAS = 30
NUM_COLUMNS = 3

# --- Funções Auxiliares ---

def falar(texto):
    """
    Função para converter texto em voz.
    ATENÇÃO: Não está sendo usada neste modelo de 30 perguntas simultâneas,
    pois falar todas as perguntas de uma vez seria inviável para o usuário.
    Mantida no código para referência futura ou se o modo de jogo mudar.
    """
    try:
        tts = gTTS(text=texto, lang='pt', slow=False)
        audio_file = "temp_audio.mp3"
        tts.save(audio_file)
        st.audio(audio_file, format='audio/mp3', start_time=0, loop=False)
        time.sleep(max(1.5, len(texto) * 0.08))
        if os.path.exists(audio_file):
            os.remove(audio_file)
    except Exception as e:
        print(f"Erro detalhado ao gerar/reproduzir áudio: {e}")
        st.warning("Não foi possível reproduzir o áudio. Verifique sua conexão com a internet ou as permissões do navegador.")


def gerar_lista_perguntas():
    """Gera uma lista de 30 perguntas de tabuada aleatórias e únicas."""
    perguntas = []
    perguntas_unicas = set()

    while len(perguntas) < TOTAL_PERGUNTAS:
        num1 = random.randint(2, 9)
        num2 = random.randint(1, 10)

        pergunta_par = (num1, num2)

        if pergunta_par not in perguntas_unicas:
            perguntas_unicas.add(pergunta_par)
            pergunta_texto = f"{num1} x {num2} = ?"
            resposta_correta = num1 * num2
            perguntas.append({'id': len(perguntas), 'pergunta': pergunta_texto, 'resposta_correta': resposta_correta})
    return perguntas

def inicializar_estado():
    """Inicializa as variáveis de estado da sessão do Streamlit."""
    if 'iniciado' not in st.session_state:
        st.session_state.iniciado = False
    if 'perguntas' not in st.session_state:
        st.session_state.perguntas = []
    if 'respostas_usuario' not in st.session_state:
        st.session_state.respostas_usuario = {}
    if 'mostrar_resultados_finais' not in st.session_state:
        st.session_state.mostrar_resultados_finais = False
    if 'acertos' not in st.session_state:
        st.session_state.acertos = 0
    if 'erros' not in st.session_state:
        st.session_state.erros = 0
    if 'last_key' not in st.session_state:
        st.session_state.last_key = time.time()

def iniciar_maratona():
    """Reinicia a maratona de perguntas."""
    st.session_state.iniciado = True
    st.session_state.perguntas = gerar_lista_perguntas()
    st.session_state.respostas_usuario = {p['id']: None for p in st.session_state.perguntas}
    st.session_state.mostrar_resultados_finais = False
    st.session_state.acertos = 0
    st.session_state.erros = 0
    st.session_state.last_key = time.time()
    st.rerun()

def verificar_todas_respostas():
    """Verifica todas as respostas do usuário e calcula o percentual."""
    acertos = 0
    erros = 0
    for pergunta_obj in st.session_state.perguntas:
        pergunta_id = pergunta_obj['id']
        resposta_correta = pergunta_obj['resposta_correta']

        input_widget_key = f"resposta_input_{pergunta_id}_{st.session_state.last_key}"
        resposta_do_campo_str = st.session_state.get(input_widget_key, '')

        if not resposta_do_campo_str or not resposta_do_campo_str.strip():
            erros += 1
            continue

        try:
            resposta_digitada = int(resposta_do_campo_str)
        except ValueError:
            erros += 1
            continue

        if resposta_digitada == resposta_correta:
            acertos += 1
        else:
            erros += 1

    st.session_state.acertos = acertos
    st.session_state.erros = erros
    st.session_state.mostrar_resultados_finais = True
    st.session_state.iniciado = False
    st.rerun()


# --- Layout do Streamlit ---

st.set_page_config(page_title="Maratona das Tabuadas", layout="wide", initial_sidebar_state="collapsed")

st.title("Maratona das Tabuadas")

inicializar_estado()

if not st.session_state.iniciado:
    st.markdown(
        f"""
        Prepare-se para exercitar suas tabuadas de **2 a 9**!
        Você terá **{TOTAL_PERGUNTAS} perguntas** aleatórias e únicas para resolver de uma vez.
        Ao final, poderá verificar seu percentual de acertos.
        """
    )
    if st.button("Iniciar Maratona", key="btn_iniciar_tela_inicial"):
        iniciar_maratona()

    if st.session_state.mostrar_resultados_finais:
        st.markdown("---")
        st.subheader("Resultados da Última Maratona:")
        st.write(f"Acertos: **{st.session_state.acertos}**")
        st.write(f"Erros: **{st.session_state.erros}**")

        percentual = (st.session_state.acertos / TOTAL_PERGUNTAS) * 100 if TOTAL_PERGUNTAS > 0 else 0
        st.write(f"Percentual de Acertos: **{percentual:.2f}%**")

        data = {'Categoria': ['Acertos', 'Erros'],
                'Quantidade': [st.session_state.acertos, st.session_state.erros]}
        df = pd.DataFrame(data)

        fig = px.pie(df, values='Quantidade', names='Categoria',
                     title='Desempenho Geral',
                     color_discrete_sequence=['#4CAF50', '#F44336'])
        fig.update_traces(textposition='inside', textinfo='percent+label')
        st.plotly_chart(fig, use_container_width=True)

        col_res1, col_res2 = st.columns(2)
        with col_res1:
            if st.button("Reiniciar Maratona", key="btn_reiniciar_apos_finalizar"):
                iniciar_maratona()
        with col_res2:
            st.info("Para finalizar, basta fechar esta aba do navegador.")

    st.markdown("---")
    st.markdown("Autora: **Márcia Romanato**")

else:
    st.subheader("Responda todas as perguntas:")

    cols = st.columns(NUM_COLUMNS)

    for i, pergunta_obj in enumerate(st.session_state.perguntas):
        col_index = i % NUM_COLUMNS
        with cols[col_index]:
            st.markdown(f"**{pergunta_obj['pergunta']}**")

            input_widget_key = f"resposta_input_{pergunta_obj['id']}_{st.session_state.last_key}"

            initial_value = st.session_state.get(input_widget_key, '')
            if initial_value is None:
                initial_value = ''

            st.text_input(
                "Sua resposta:",
                key=input_widget_key,
                value=initial_value,
                # REMOVIDO: type="number", pois não é um tipo válido para st.text_input
                max_chars=3
            )
            st.markdown("---")

    st.markdown("---")
    if st.button("Verificar Respostas", key="btn_verificar_respostas"):
        verificar_todas_respostas()

    st.markdown("---")
    st.markdown("Autora: **Márcia Romanato**")